### ISSUE TITLE
Reason of Blurry Images

### ISSUE THREAD

**Issue by QiSiyu** [kuoteng/JPEG#1]
Hi, I'm using your codec to compress JPEG images and it works fantastic! 
Just to let you know, I've figured out why encoded JPEG images are blurry: in line 105 of encoder.c: the denominator should be changed from "zigzag_quantize_table" to "quantize_table", since "tmp" matrix isn't in zigzag order.
Thanks again!

**Comment by Rivenna36870** [comment]
Thanks for your reply, it's my pleasure that my code helps you, and really thank you for let me know the bug it had!
I'll check it out these days :)

**Comment by rapirent** [comment]
Really thank you for letting me know the bug it had!
I'll check it out these days :)

**Comment by rapirent** [comment]
resolved in commit 4b4fa74
